#include "Bosses/AbelPoses.h"
#include "AnimationRuntime.h"
#include "ReferenceSkeleton.h"

namespace
{
	// The table itself, generated by Tools/abel_poses.py (don't edit it by hand).
#include "Bosses/AbelPoseData.inl"

	bool IsValidBone(int32 Bone)
	{
		return Bone >= 0 && Bone < GeneratedBoneCount;
	}

	const FAbelPoseBone& Row(EAbelPose Pose, int32 Bone)
	{
		const int32 Index = FMath::Clamp(static_cast<int32>(Pose), 0, static_cast<int32>(EAbelPose::Count) - 1);
		return GeneratedPoses[Index][Bone];
	}
}

namespace AbelPoses
{
	int32 NumBones()
	{
		return GeneratedBoneCount;
	}

	FName BoneName(int32 Bone)
	{
		return IsValidBone(Bone) ? FName(GeneratedBones[Bone].Name) : NAME_None;
	}

	int32 FindBone(FName Name)
	{
		for (int32 Bone = 0; Bone < GeneratedBoneCount; ++Bone)
		{
			if (Name == FName(GeneratedBones[Bone].Name))
			{
				return Bone;
			}
		}
		return INDEX_NONE;
	}

	int32 ParentOf(int32 Bone)
	{
		return IsValidBone(Bone) && GeneratedBones[Bone].Parent >= 0 ? GeneratedBones[Bone].Parent : INDEX_NONE;
	}

	FVector RestHead(int32 Bone)
	{
		if (!IsValidBone(Bone))
		{
			return FVector::ZeroVector;
		}
		const float* Rest = GeneratedBones[Bone].Rest;
		return FVector(Rest[0], Rest[1], Rest[2]);
	}

	FQuat Own(EAbelPose Pose, int32 Bone)
	{
		if (!IsValidBone(Bone))
		{
			return FQuat::Identity;
		}
		const float* Q = Row(Pose, Bone).Own;
		return FQuat(Q[0], Q[1], Q[2], Q[3]).GetNormalized();
	}

	FVector Shift(EAbelPose Pose, int32 Bone)
	{
		if (!IsValidBone(Bone))
		{
			return FVector::ZeroVector;
		}
		const float* S = Row(Pose, Bone).Shift;
		return FVector(S[0], S[1], S[2]);
	}

	const TCHAR* Name(EAbelPose Pose)
	{
		static const TCHAR* const Names[] = { TEXT("idle"), TEXT("flare"), TEXT("fire"), TEXT("lunge"), TEXT("sunset"), TEXT("kneel"), TEXT("sit") };
		static_assert(UE_ARRAY_COUNT(Names) == static_cast<int32>(EAbelPose::Count), "A name per pose");
		const int32 Index = static_cast<int32>(Pose);
		return Index >= 0 && Index < static_cast<int32>(EAbelPose::Count) ? Names[Index] : TEXT("?");
	}

	TArray<FName> ExtraBones()
	{
		return { TEXT("lantern"), TEXT("gun"), TEXT("skirt_f_01"), TEXT("skirt_f_02"), TEXT("skirt_l_01"), TEXT("skirt_r_01") };
	}

	bool LaysShroud(EAbelPose Pose)
	{
		return Pose == EAbelPose::Kneel || Pose == EAbelPose::Sit;
	}

	FAbelPoseHeads SolveHeads(EAbelPose Pose)
	{
		// Parents come before their children in the table, so one pass poses them all: a bone's joint rides where its
		// parent's turn carries it, then its own shift; its turn is its parent's with its own on top.
		FAbelPoseHeads Solved;
		Solved.Heads.SetNum(GeneratedBoneCount);
		Solved.Turns.SetNum(GeneratedBoneCount);
		for (int32 Bone = 0; Bone < GeneratedBoneCount; ++Bone)
		{
			const int32 Parent = ParentOf(Bone);
			const FQuat Above = Parent != INDEX_NONE ? Solved.Turns[Parent] : FQuat::Identity;
			const FVector Carried = Parent != INDEX_NONE ? Solved.Heads[Parent] + Above.RotateVector(RestHead(Bone) - RestHead(Parent)) : RestHead(Bone);
			Solved.Heads[Bone] = Carried + Shift(Pose, Bone);
			Solved.Turns[Bone] = (Above * Own(Pose, Bone)).GetNormalized();
		}
		return Solved;
	}

	TArray<FTransform> Solve(const FReferenceSkeleton& Skeleton, EAbelPose Pose)
	{
		const int32 Count = Skeleton.GetNum();
		TArray<FTransform> Rest;
		TArray<FTransform> Posed;
		TArray<FQuat> Turned;
		Rest.SetNum(Count);
		Posed.SetNum(Count);
		Turned.SetNum(Count);
		// A skeleton lists every bone after its parent.
		for (int32 Index = 0; Index < Count; ++Index)
		{
			Rest[Index] = FAnimationRuntime::GetComponentSpaceTransformRefPose(Skeleton, Index);
			const int32 Parent = Skeleton.GetParentIndex(Index);
			const int32 Bone = FindBone(Skeleton.GetBoneName(Index));
			const FQuat Above = Parent != INDEX_NONE ? Turned[Parent] : FQuat::Identity;
			FVector Joint = Parent != INDEX_NONE
				? Posed[Parent].GetLocation() + Above.RotateVector(Rest[Index].GetLocation() - Rest[Parent].GetLocation())
				: Rest[Index].GetLocation();
			FQuat OwnTurn = FQuat::Identity;
			if (Bone != INDEX_NONE)
			{
				Joint += Shift(Pose, Bone);
				OwnTurn = Own(Pose, Bone);
			}
			Turned[Index] = (Above * OwnTurn).GetNormalized();
			Posed[Index] = FTransform(Turned[Index] * Rest[Index].GetRotation(), Joint, Rest[Index].GetScale3D());
		}
		return Posed;
	}

	FVector FireMuzzle()
	{
		return FVector(GeneratedFireMuzzle);
	}

	FVector FlareGlobe()
	{
		return FVector(GeneratedFlareGlobe);
	}

	FVector KneelPumpHead()
	{
		return FVector(GeneratedKneelGun);
	}

	FQuat KneelPumpTurn()
	{
		return FQuat(GeneratedKneelGunTurn).GetNormalized();
	}
}
