#pragma once

#include "CoreMinimal.h"

struct FReferenceSkeleton;

/**
 * Abel's poses (Art/Models/Creatures/Abel.py's pose table, approved with his model): the fight's idle (the lantern arm
 * across the coal, the pump low), the lantern's flare before the buckshot, the shot, the stock lunge (the pump turned on its
 * bone so the butt leads), the turn to the sunset (the lantern lowered: his coal open), the kneel at zero (the pump laid on
 * the boards) and the sit on his bier after the fight.
 */
enum class EAbelPose : uint8
{
	Idle,
	Flare,
	Fire,
	Lunge,
	Sunset,
	Kneel,
	Sit,
	Count
};

/** One bone of the table: its name, its parent among the table's bones (-1: under the armature's root), its head at rest (cm). */
struct FAbelPoseBoneInfo
{
	const TCHAR* Name;
	int32 Parent;
	float Rest[3];
};

/** One bone in one pose: its own turn under its parent's (FQuat X, Y, Z, W) and its shift (cm). */
struct FAbelPoseBone
{
	float Own[4];
	float Shift[3];
};

/** A pose's bones as the table puts them, worked out without a skeleton: each one's head (cm) and whole turn from rest. */
struct FAbelPoseHeads
{
	TArray<FVector> Heads;
	TArray<FQuat> Turns;
};

/**
 * The pose table as the game reads it: Bosses/AbelPoseData.inl, generated by Tools/abel_poses.py from the table Abel.py
 * writes (Intermediate/AbelModel/Abel_poses.json), so the poses live in the code and the model script stays their source.
 * Component space at size 1 (cm; X forward, Y right, Z up): the actor scales him 1.3. A bone's turn is about its own joint
 * under its parent's (AUnpaidCreature's Turned = Above * Own), and a bone whose head leaves where its parent carries it is
 * shifted (the pelvis in the lunge, the kneel and the sit; the shroud's tail_01 and the coat's side bones knelt and sat; the
 * pump laid on the boards in the kneel).
 */
namespace AbelPoses
{
	/** The table's bones (39: the Unpaid's, and lantern, gun, skirt_f_01, skirt_f_02, skirt_l_01 and skirt_r_01). */
	AI_LOOTER_SHOOTER_API int32 NumBones();
	AI_LOOTER_SHOOTER_API FName BoneName(int32 Bone);
	/** A bone's index in the table, or INDEX_NONE. */
	AI_LOOTER_SHOOTER_API int32 FindBone(FName Name);
	/** Its parent's index in the table, or INDEX_NONE under the root. */
	AI_LOOTER_SHOOTER_API int32 ParentOf(int32 Bone);
	/** Its head at rest (cm, size 1), as the table measured it on the model. */
	AI_LOOTER_SHOOTER_API FVector RestHead(int32 Bone);

	AI_LOOTER_SHOOTER_API FQuat Own(EAbelPose Pose, int32 Bone);
	AI_LOOTER_SHOOTER_API FVector Shift(EAbelPose Pose, int32 Bone);

	/** "idle", "flare", ...: the table's names. */
	AI_LOOTER_SHOOTER_API const TCHAR* Name(EAbelPose Pose);

	/** The bones the Unpaid's rig lacks, which Abel's poses move too. */
	AI_LOOTER_SHOOTER_API TArray<FName> ExtraBones();

	/** Knelt and sat, his shroud lies where the table lays it: the chains' swing mustn't move its links. */
	AI_LOOTER_SHOOTER_API bool LaysShroud(EAbelPose Pose);

	/** Every bone's head and whole turn in Pose, from the table's own rest heads (no model needed: the tests' measure). */
	AI_LOOTER_SHOOTER_API FAbelPoseHeads SolveHeads(EAbelPose Pose);

	/**
	 * Every bone of Skeleton in component space in Pose (indexed as the skeleton is), posed as AUnpaidCreature poses its
	 * rig: a bone the table lacks (the root) keeps its rest place under its parent. The seated friend's pose.
	 */
	AI_LOOTER_SHOOTER_API TArray<FTransform> Solve(const FReferenceSkeleton& Skeleton, EAbelPose Pose);

	/** Where the pump's muzzle is in the shot, and the lantern's globe in the flare (component space, size 1). */
	AI_LOOTER_SHOOTER_API FVector FireMuzzle();
	AI_LOOTER_SHOOTER_API FVector FlareGlobe();

	/** Where the kneel lays the pump on the boards: the gun bone's head and whole turn (component space, size 1). */
	AI_LOOTER_SHOOTER_API FVector KneelPumpHead();
	AI_LOOTER_SHOOTER_API FQuat KneelPumpTurn();
}
