"""Writes assets.js: the HUD's pictures and font inlined as data URIs, so this folder holds no binary files (the cloud
sessions can't upload Git LFS objects). The pictures are the Inked icons drawn by Art/Icons/InkedIcons.py's draw()
(rifle and shotgun at 168 x 90 and 174 x 42, their ammo at 60 x 60); the font is Chakra Petch Bold (SIL Open Font
License), so the HUD draws in its own face even where Google Fonts doesn't load.

    python3 Tools/StyleLab/web/hud/inline_assets.py <folder with rifle.png, shotgun.png, ammo_rifle.png,
                                                     ammo_shotgun.png, ChakraPetch-Bold.woff2>
"""
import base64
import os
import sys

SRC = sys.argv[1]
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'assets.js')


def data_uri(name, mime):
    with open(os.path.join(SRC, name), 'rb') as f:
        return f'data:{mime};base64,' + base64.b64encode(f.read()).decode('ascii')


lines = ['// Generated by inline_assets.py: the Inked icons and Chakra Petch Bold as data URIs. Do not edit by hand.']
lines.append('export const ICONS = {')
lines.append(f"\trifle: '{data_uri('rifle.png', 'image/png')}',")
lines.append(f"\tshotgun: '{data_uri('shotgun.png', 'image/png')}',")
lines.append('};')
lines.append('export const AMMO = {')
lines.append(f"\trifle: '{data_uri('ammo_rifle.png', 'image/png')}',")
lines.append(f"\tshotgun: '{data_uri('ammo_shotgun.png', 'image/png')}',")
lines.append('};')
lines.append(f"export const FONT = '{data_uri('ChakraPetch-Bold.woff2', 'font/woff2')}';")
with open(OUT, 'w', newline='\n') as f:
    f.write('\n'.join(lines) + '\n')
print(f'{OUT}: {os.path.getsize(OUT) / 1024:.0f} KB')
