#include "Story/AmosPoses.h"
#include "AnimationRuntime.h"
#include "ReferenceSkeleton.h"

namespace
{
	// The table itself, generated by Tools/amos_poses.py (don't edit it by hand).
#include "Story/AmosPoseData.inl"

	bool IsValidBone(int32 Bone)
	{
		return Bone >= 0 && Bone < GeneratedBoneCount;
	}

	const FAmosPoseBone& Row(EAmosPose Pose, int32 Bone)
	{
		const int32 Index = FMath::Clamp(static_cast<int32>(Pose), 0, static_cast<int32>(EAmosPose::Count) - 1);
		return GeneratedPoses[Index][Bone];
	}

	/** The head's extra turn about the body's up axis, and the jaw's opening as the talk pose opens it. */
	FQuat HeadTurn(const FAmosPoseLayer& Layer)
	{
		return FQuat(FVector::UpVector, FMath::DegreesToRadians(Layer.HeadYaw));
	}

	FQuat JawOpening(const FAmosPoseLayer& Layer, int32 Jaw)
	{
		const float Open = FMath::Clamp(Layer.JawOpen, 0.f, 1.f);
		return Open > 0.f ? FQuat::Slerp(FQuat::Identity, AmosPoses::Own(EAmosPose::Talk, Jaw), Open).GetNormalized() : FQuat::Identity;
	}

	/** A bone's whole turn: its parent's with its own on top, the layer's head turn and jaw added where they belong. */
	FQuat Turned(const FQuat& Above, EAmosPose Pose, int32 Bone, const FAmosPoseLayer& Layer, int32 Head, int32 Jaw)
	{
		FQuat OwnTurn = AmosPoses::Own(Pose, Bone);
		if (Bone == Jaw)
		{
			OwnTurn = (OwnTurn * JawOpening(Layer, Jaw)).GetNormalized();
		}
		const FQuat Whole = (Above * OwnTurn).GetNormalized();
		// Turned about the body's up at the head's joint; the jaw and the hat ride it as its children.
		return Bone == Head && Layer.HeadYaw != 0.f ? (HeadTurn(Layer) * Whole).GetNormalized() : Whole;
	}
}

namespace AmosPoses
{
	int32 NumBones()
	{
		return GeneratedBoneCount;
	}

	FName BoneName(int32 Bone)
	{
		return IsValidBone(Bone) ? FName(GeneratedBones[Bone].Name) : NAME_None;
	}

	int32 FindBone(FName Name)
	{
		for (int32 Bone = 0; Bone < GeneratedBoneCount; ++Bone)
		{
			if (Name == FName(GeneratedBones[Bone].Name))
			{
				return Bone;
			}
		}
		return INDEX_NONE;
	}

	int32 ParentOf(int32 Bone)
	{
		return IsValidBone(Bone) && GeneratedBones[Bone].Parent >= 0 ? GeneratedBones[Bone].Parent : INDEX_NONE;
	}

	FVector RestHead(int32 Bone)
	{
		if (!IsValidBone(Bone))
		{
			return FVector::ZeroVector;
		}
		const float* Rest = GeneratedBones[Bone].Rest;
		return FVector(Rest[0], Rest[1], Rest[2]);
	}

	FQuat Own(EAmosPose Pose, int32 Bone)
	{
		if (!IsValidBone(Bone))
		{
			return FQuat::Identity;
		}
		const float* Q = Row(Pose, Bone).Own;
		return FQuat(Q[0], Q[1], Q[2], Q[3]).GetNormalized();
	}

	FVector Shift(EAmosPose Pose, int32 Bone)
	{
		if (!IsValidBone(Bone))
		{
			return FVector::ZeroVector;
		}
		const float* S = Row(Pose, Bone).Shift;
		return FVector(S[0], S[1], S[2]);
	}

	const TCHAR* Name(EAmosPose Pose)
	{
		static const TCHAR* const Names[] = { TEXT("idle"), TEXT("lean"), TEXT("sit"), TEXT("talk") };
		static_assert(UE_ARRAY_COUNT(Names) == static_cast<int32>(EAmosPose::Count), "A name per pose");
		const int32 Index = static_cast<int32>(Pose);
		return Index >= 0 && Index < static_cast<int32>(EAmosPose::Count) ? Names[Index] : TEXT("?");
	}

	TArray<FName> ExtraBones()
	{
		return { TEXT("skirt_f_01"), TEXT("skirt_f_02"), TEXT("fork") };
	}

	float LeanBack()
	{
		return GeneratedLeanBack;
	}

	float SitTurn()
	{
		return GeneratedSitTurn;
	}

	FVector SpeakerFromHead()
	{
		return FVector(GeneratedSpeakerFromHead);
	}

	FAmosPoseHeads SolveHeads(EAmosPose Pose, const FAmosPoseLayer& Layer)
	{
		// Parents come before their children in the table, so one pass poses them all: a bone's joint rides where its
		// parent's turn carries it, then its own shift; its turn is its parent's with its own on top.
		const int32 Head = FindBone(TEXT("head"));
		const int32 Jaw = FindBone(TEXT("jaw"));
		FAmosPoseHeads Solved;
		Solved.Heads.SetNum(GeneratedBoneCount);
		Solved.Turns.SetNum(GeneratedBoneCount);
		for (int32 Bone = 0; Bone < GeneratedBoneCount; ++Bone)
		{
			const int32 Parent = ParentOf(Bone);
			const FQuat Above = Parent != INDEX_NONE ? Solved.Turns[Parent] : FQuat::Identity;
			const FVector Carried = Parent != INDEX_NONE ? Solved.Heads[Parent] + Above.RotateVector(RestHead(Bone) - RestHead(Parent)) : RestHead(Bone);
			Solved.Heads[Bone] = Carried + Shift(Pose, Bone);
			Solved.Turns[Bone] = Turned(Above, Pose, Bone, Layer, Head, Jaw);
		}
		return Solved;
	}

	TArray<FTransform> Solve(const FReferenceSkeleton& Skeleton, EAmosPose Pose, const FAmosPoseLayer& Layer)
	{
		const int32 Head = FindBone(TEXT("head"));
		const int32 Jaw = FindBone(TEXT("jaw"));
		const int32 Count = Skeleton.GetNum();
		TArray<FTransform> Rest;
		TArray<FTransform> Posed;
		TArray<FQuat> Turns;
		Rest.SetNum(Count);
		Posed.SetNum(Count);
		Turns.SetNum(Count);
		// A skeleton lists every bone after its parent.
		for (int32 Index = 0; Index < Count; ++Index)
		{
			Rest[Index] = FAnimationRuntime::GetComponentSpaceTransformRefPose(Skeleton, Index);
			const int32 Parent = Skeleton.GetParentIndex(Index);
			const int32 Bone = FindBone(Skeleton.GetBoneName(Index));
			const FQuat Above = Parent != INDEX_NONE ? Turns[Parent] : FQuat::Identity;
			FVector Joint = Parent != INDEX_NONE
				? Posed[Parent].GetLocation() + Above.RotateVector(Rest[Index].GetLocation() - Rest[Parent].GetLocation())
				: Rest[Index].GetLocation();
			if (Bone != INDEX_NONE)
			{
				Joint += Shift(Pose, Bone);
				Turns[Index] = Turned(Above, Pose, Bone, Layer, Head, Jaw);
			}
			else
			{
				Turns[Index] = Above;
			}
			Posed[Index] = FTransform(Turns[Index] * Rest[Index].GetRotation(), Joint, Rest[Index].GetScale3D());
		}
		return Posed;
	}

	TArray<FTransform> Blend(const TArray<FTransform>& From, const TArray<FTransform>& To, float Alpha)
	{
		const float Share = FMath::Clamp(Alpha, 0.f, 1.f);
		if (From.Num() != To.Num() || Share >= 1.f)
		{
			return To;
		}
		TArray<FTransform> Blended;
		Blended.SetNum(From.Num());
		for (int32 Index = 0; Index < From.Num(); ++Index)
		{
			Blended[Index] = FTransform(FQuat::Slerp(From[Index].GetRotation(), To[Index].GetRotation(), Share).GetNormalized(),
				FMath::Lerp(From[Index].GetLocation(), To[Index].GetLocation(), static_cast<double>(Share)),
				FMath::Lerp(From[Index].GetScale3D(), To[Index].GetScale3D(), static_cast<double>(Share)));
		}
		return Blended;
	}

	float HeadYawOf(EAmosPose Pose)
	{
		const int32 Head = FindBone(TEXT("head"));
		const FAmosPoseHeads Solved = SolveHeads(Pose);
		if (!Solved.Turns.IsValidIndex(Head))
		{
			return 0.f;
		}
		const FVector Looking = Solved.Turns[Head].RotateVector(FVector::ForwardVector);
		return FMath::RadiansToDegrees(static_cast<float>(FMath::Atan2(Looking.Y, Looking.X)));
	}
}
