#pragma once

#include "CoreMinimal.h"

struct FReferenceSkeleton;

/**
 * Amos's poses (Art/Models/Creatures/Amos.py's pose table, approved with his model): the idle (his bind pose: upright, the
 * fork upright in his right fist), the lean on his fence's top rail (forearms folded on it, the fork let go and leaning on
 * the post at his right), the sit on the rail after Side 2 (the knees bent back, the shroud trailing back between the
 * rails, the fork standing on the ground in his fist, his head turned into the low sun) and the talk (the idle with the
 * jaw open, layered on any pose).
 */
enum class EAmosPose : uint8
{
	Idle,
	Lean,
	Sit,
	Talk,
	Count
};

/** One bone of the table: its name, its parent among the table's bones (-1: under the armature's root), its head at rest (cm). */
struct FAmosPoseBoneInfo
{
	const TCHAR* Name;
	int32 Parent;
	float Rest[3];
};

/** One bone in one pose: its own turn under its parent's (FQuat X, Y, Z, W) and its shift (cm). */
struct FAmosPoseBone
{
	float Own[4];
	float Shift[3];
};

/** A pose's bones as the table puts them, worked out without a skeleton: each one's head (cm) and whole turn from rest. */
struct FAmosPoseHeads
{
	TArray<FVector> Heads;
	TArray<FQuat> Turns;
};

/** What a pose carries on top of the table while he talks: his head turned to the listener, his jaw moving. */
struct FAmosPoseLayer
{
	/** Degrees his head turns about the body's up axis at its joint, on top of the pose's own turn (+: to his right). */
	float HeadYaw = 0.f;

	/** How far his jaw is open, 0 shut to 1 the talk pose's open jaw (8 degrees). */
	float JawOpen = 0.f;
};

/**
 * The pose table as the game reads it: Story/AmosPoseData.inl, generated by Tools/amos_poses.py from the table Amos.py
 * writes (Intermediate/AmosModel/Amos_poses.json), so the poses live in the code and the model script stays their source.
 * Component space at size 1 (cm; X forward, Y right, Z up). A bone's turn is about its own joint under its parent's
 * (AUnpaidCreature's Turned = Above * Own), and a bone whose head leaves where its parent carries it is shifted (the pelvis
 * lifted onto the rail in the sit; the shroud's tail_01 riding the knees in the lean and the sit; the fork let go in the
 * lean and stood on the ground in the sit).
 */
namespace AmosPoses
{
	/** The table's bones (36: the Unpaid's, and skirt_f_01, skirt_f_02 and fork). */
	AI_LOOTER_SHOOTER_API int32 NumBones();
	AI_LOOTER_SHOOTER_API FName BoneName(int32 Bone);
	/** A bone's index in the table, or INDEX_NONE. */
	AI_LOOTER_SHOOTER_API int32 FindBone(FName Name);
	/** Its parent's index in the table, or INDEX_NONE under the root. */
	AI_LOOTER_SHOOTER_API int32 ParentOf(int32 Bone);
	/** Its head at rest (cm, size 1), as the table measured it on the model. */
	AI_LOOTER_SHOOTER_API FVector RestHead(int32 Bone);

	AI_LOOTER_SHOOTER_API FQuat Own(EAmosPose Pose, int32 Bone);
	AI_LOOTER_SHOOTER_API FVector Shift(EAmosPose Pose, int32 Bone);

	/** "idle", "lean", "sit", "talk": the table's names. */
	AI_LOOTER_SHOOTER_API const TCHAR* Name(EAmosPose Pose);

	/** The bones the Unpaid's rig lacks, which Amos's poses move too. */
	AI_LOOTER_SHOOTER_API TArray<FName> ExtraBones();

	/** Leaning on the fence, his origin stands this far behind the fence's line (cm), square to it and facing it. */
	AI_LOOTER_SHOOTER_API float LeanBack();

	/** Sitting on it, his origin is on the fence's line, turned this far to his right from square (degrees). */
	AI_LOOTER_SHOOTER_API float SitTurn();

	/** His speaker point (SOCKET_Speaker on his hat, at his mouth) from the head bone's head at rest (cm). */
	AI_LOOTER_SHOOTER_API FVector SpeakerFromHead();

	/**
	 * Every bone's head and whole turn in Pose with Layer on top, from the table's own rest heads (no model needed: the
	 * tests' measure, and where his head and his speaker point are without his model).
	 */
	AI_LOOTER_SHOOTER_API FAmosPoseHeads SolveHeads(EAmosPose Pose, const FAmosPoseLayer& Layer = FAmosPoseLayer());

	/**
	 * Every bone of Skeleton in component space in Pose with Layer on top (indexed as the skeleton is), posed as
	 * AUnpaidCreature poses its rig: a bone the table lacks (the root) keeps its rest place under its parent.
	 */
	AI_LOOTER_SHOOTER_API TArray<FTransform> Solve(const FReferenceSkeleton& Skeleton, EAmosPose Pose,
		const FAmosPoseLayer& Layer = FAmosPoseLayer());

	/** Two solved poses blended bone by bone, Alpha of the way from From to To (locations lerped, turns slerped). */
	AI_LOOTER_SHOOTER_API TArray<FTransform> Blend(const TArray<FTransform>& From, const TArray<FTransform>& To, float Alpha);

	/** How far the pose turns his head from his body's front (degrees about up; +: to his right): the sit's look into the sun. */
	AI_LOOTER_SHOOTER_API float HeadYawOf(EAmosPose Pose);
}
